CREATE TABLE IF NOT EXISTS companies (
	company_id BIGSERIAL NOT NULL PRIMARY KEY,
	code VARCHAR ( 255 ) NOT NULL,
	name TEXT,
	region  VARCHAR ( 255 ) NOT NULL,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	update_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	delete_at TIMESTAMP
);

CREATE TABLE IF NOT EXISTS organizations (
    organization_id BIGSERIAL NOT NULL PRIMARY KEY,
	company_code VARCHAR REFERENCES companies(code),
	code VARCHAR ( 255 ) NOT NULL,
	name TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	update_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	delete_at TIMESTAMP
);


CREATE TABLE IF NOT EXISTS schedules (
    schedule_id BIGSERIAL NOT NULL PRIMARY KEY,
	organization_id BIGINT REFERENCES organizations(organization_id),
	date VARCHAR ( 255 ) NOT NULL,
	from_time VARCHAR ( 255 )  NOT NULL,
	to_time VARCHAR ( 255 )  NOT NULL,
	area TEXT  NOT NULL,
	reason TEXT,
	created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	update_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
	delete_at TIMESTAMP
);